### ISSUE TITLE
wonder the gt of event classes?

### ISSUE THREAD

**Issue by vhzy** [ByZ0e/Glance-Focus#1]
great work!
I wonder how do you get the number of event classes in section4.1.
For example STAR offers 111 action classes on their official website, according to section4.1, the gt of event classes is 157.
And also, in fig3, a prediction is 'holding a dish' which is not found in action classes of STAR.
Do I miss anything here? Thank U!

**Comment by ByZ0e** [comment]
Thanks for your interest. Since the videos in the STAR and AGQA datasets are all from the Charades dataset. We uniformly use the action annotations provided by Chardes as the groundtruth. Please refer to https://prior.allenai.org/projects/charades. However, STAR did perform some filtering, resulting in some differences as you said.
